name: cost-accounting-benchmark-CI

on:
  push:
    paths:
    - 'java/cost-accounting-benchmark/**'
    - '.github/**'
  pull_request:
  workflow_dispatch:

jobs:
  Build:
    runs-on: [self-hosted, docker]
    permissions:
      checks: write
    timeout-minutes: 30
    container:
      image:  ghcr.io/project-tsurugi/oltp-sandbox:latest
      credentials:
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GHCR_PAT }}
      volumes:
        - ${{ vars.gradle_cache_dir }}:/root/.gradle
    defaults:
      run:
        shell: bash
        working-directory: java/cost-accounting-benchmark
    env:
      JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF8
      GPR_USER: ${{ github.repository_owner }}
      GPR_KEY: ${{ secrets.GHCR_PAT }}

    steps:
      - name: Setup_Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Checkout
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GHA_PAT }}

      - name: Assemble
        run: |
          ./gradlew -i showTsubakuroManifest showIceaxeManifest clean assemble

      - name: Check
        run: |
          ./gradlew -i check --continue

      - name: Verify
        uses: project-tsurugi/tsurugi-annotations-action@v1
        if: always()
        with:
          junit_input: 'java/cost-accounting-benchmark/build/test-results/**/TEST-*.xml'
          junit_test_src_dir: 'java/cost-accounting-benchmark/src/test/java'
          spotbugs_input: 'java/cost-accounting-benchmark/build/reports/spotbugs/main/*.xml'
