name: cost-batch-benchmark-CI

on:
  push:
    paths:
    - 'cost-accounting/java/example-nedo'
    - '.github/**'
  pull_request:

jobs:
  Build:
    runs-on: [self-hosted, docker]
    timeout-minutes: 30
    container:
      image:  ghcr.io/project-tsurugi/oltp-sandbox:latest
      credentials:
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GHCR_PAT }}
      volumes:
        - /work/docker-cache/.gradle:/root/.gradle
    defaults:
      run:
        shell: bash
        working-directory: cost-accounting/java/example-nedo
    env:
      JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF8

    steps:
      - id: Checkout
        name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive
          token: ${{ secrets.GHA_PAT }}

      - id: Assemble
        name: Assemble
        run: |
          ./gradlew -i clean assemble

      - id: Test
        name: Test
        continue-on-error: false
        run: |
          ./gradlew -i test

      - id: Static_Analysis
        name: Static_Analysis
        run: |
          ./gradlew -i spotbugsMain -Pci

      - id: Generate_Annotations
        name: Generate_Annotations
        uses: ./.github/actions/tsurugi-annotations-action
        if: always()
        with:
          junit_input: 'cost-accounting/java/example-nedo/build/test-results/**/TEST-*.xml'
          junit_test_src_dir: 'cost-accounting/java/example-nedo/src/test/java'
          spotbugs_input: 'cost-accounting/java/example-nedo/build/reports/spotbugs/main/*.xml'

      - id: Notify_Slack
        name: Notify_Slack
        uses: ./.github/actions/tsurugi-slack-action
        if: always() && (contains(github.ref, '/tags/') || contains(github.ref, '/pull/') || contains(github.ref, '/heads/master'))
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        with:
          kind: 'job-result'
          channel: 'tsurugi-batchapp-benchmark'
          status: ${{ job.status }}
          step_context: ${{ toJson(steps) }}
          username: ${{ github.workflow }}
